"""Append the 13 missing-battle rows (IDs 693-705) to movements.csv."""
import csv

FIELDS = ['id','side','force','commander','units','date_start','date_end',
          'event_type','from_place','to_place','action_place','description',
          'confidence','source','note']

ROWS = [
    dict(id=693, side='Boer', force="Battle of Lombard's Kop",
         commander='Joubert, Piet', units="Natal Commandos",
         date_start='1899-10-30', date_end='1899-10-30',
         event_type='defeat', action_place="Lombard's Kop",
         description="British sortie from Ladysmith repulsed at Lombard's Kop on 30 Oct 1899; White's force beaten back with heavy loss, completing Boer encirclement of Ladysmith and sealing in 12,000 men for four months.",
         confidence='high', source='Conan Doyle ch.V', note=''),
    dict(id=694, side='British', force="Battle of Dreifontein",
         commander='Roberts, Lord', units="6th Division; Cavalry Division",
         date_start='1900-03-10', date_end='1900-03-10',
         event_type='engagement', action_place='Dreifontein',
         description="Roberts's advance force defeated De Wet's rearguard at Dreifontein (10 Mar 1900), opening the road to Bloemfontein; one of the sharp conventional engagements during the OFS advance with over 400 Boer casualties.",
         confidence='high', source='Conan Doyle ch.XVI', note=''),
    dict(id=695, side='British', force="Battle of Karee Siding",
         commander='Tucker, C.', units="7th Division",
         date_start='1900-03-29', date_end='1900-03-29',
         event_type='engagement', action_place='Karee Siding',
         description="Tucker's 7th Division engaged a Boer rearguard at Karee Siding north of Bloemfontein on 29 Mar 1900, pushing the Boers back from their kopje positions after a day-long fight and maintaining Roberts's advance.",
         confidence='high', source='Conan Doyle ch.XVII', note=''),
    dict(id=696, side='Boer', force="Battle of Sannaspos (Koorn Spruit)",
         commander='De Wet, Christiaan', units="De Wet's commando; Sarel Eloff's men",
         date_start='1900-03-31', date_end='1900-03-31',
         event_type='raid', action_place='Sannaspos',
         description="De Wet ambushed Broadwood's column at Koorn Spruit/Sannaspos (31 Mar 1900) east of Bloemfontein, capturing 7 guns, 117 wagons and 430 prisoners in the most brilliant Boer coup of the conventional phase.",
         confidence='high', source='Conan Doyle ch.XVII', note=''),
    dict(id=697, side='Boer', force="Siege of Wepener",
         commander='Olivier, J.H.', units="Olivier's OFS commando (~5,000)",
         date_start='1900-04-09', date_end='1900-04-25',
         event_type='siege', action_place='Wepener',
         description="Olivier's OFS commando besieged the Colonial and Cape garrison at Wepener 9-25 Apr 1900; 1,900 defenders held out for 16 days until relieved by Rundle, tying down 5,000 Boers during Roberts's critical advance.",
         confidence='high', source='Conan Doyle ch.XVII', note=''),
    dict(id=698, side='British', force="Relief of Mafeking",
         commander='Mahon, B.T.', units="Mahon's Relief Column; Plumer's Rhodesian Regiment",
         date_start='1900-05-17', date_end='1900-05-17',
         event_type='capture', action_place='Mafeking',
         description="Mafeking relieved 17 May 1900 by Mahon's flying column from the south and Plumer from the north, ending Baden-Powell's 217-day siege; news caused jubilant celebrations ('mafficking') across the British Empire.",
         confidence='high', source='Conan Doyle ch.XV', note=''),
    dict(id=699, side='Boer', force="Battle of Helvetia",
         commander='Grobler, P.J.', units="Eastern Transvaal commandos",
         date_start='1901-01-29', date_end='1901-01-29',
         event_type='raid', action_place='Helvetia',
         description="Boer commandos under P.J. Grobler stormed the British fort at Helvetia on 29 Jan 1901, capturing the entire 113th Battery RFA (5 guns) and 200 prisoners; one of the most audacious guerrilla raids of 1901.",
         confidence='high', source='angloboerwar.com', note=''),
    dict(id=700, side='British', force="Colesburg Operations",
         commander='French, J.D.P.', units="Cavalry Brigade; 1st Division detachments",
         date_start='1899-12-01', date_end='1900-01-15',
         event_type='engagement', action_place='Colesburg',
         description="Gen French conducted a skilful holding action around Colesburg Dec 1899-Jan 1900, fixing Boer forces on the northern Cape front and preventing deeper invasion of the Colony while Roberts organised the main advance.",
         confidence='high', source='Conan Doyle ch.XIII', note=''),
    dict(id=701, side='Boer', force="Siege of O'kiep (Okiep)",
         commander='Smuts, Jan', units="Smuts's Cape commando (~300)",
         date_start='1902-04-01', date_end='1902-05-04',
         event_type='siege', action_place="Okiep",
         description="Smuts besieged the copper-mining town of O'kiep in Namaqualand Apr-May 1902, holding out until the Peace of Vereeniging; one of the last active operations of the entire war.",
         confidence='high', source='angloboerwar.com', note=''),
    dict(id=702, side='Boer', force="Cronjé surrenders at Paardeberg",
         commander='Cronjé, Piet', units="Cronjé's OFS/Transvaal force (~4,000 burghers)",
         date_start='1900-02-27', date_end='1900-02-27',
         event_type='surrender', action_place='Paardeberg',
         description="Piet Cronjé and ~4,000 burghers surrendered to Lord Roberts at Paardeberg on 27 Feb 1900 (Majuba Day) after a 10-day siege; the largest Boer surrender of the war and the turning point of the conventional phase.",
         confidence='high', source='Conan Doyle ch.XIV', note=''),
    dict(id=703, side='Boer', force="Smuts's Raid — Barkly East sector",
         commander='Smuts, Jan', units="Smuts's commando (~300)",
         date_start='1901-09-15', date_end='1901-11-01',
         event_type='raid', action_place='Barkly East',
         description="Smuts's Cape commando operated in the Barkly East highlands Sep-Oct 1901, recruiting Cape rebels and gathering remounts in the eastern mountain passes while evading British pursuit columns.",
         confidence='high', source='angloboerwar.com', note=''),
    dict(id=704, side='Boer', force="Smuts's Raid — Lady Grey / Dordrecht",
         commander='Smuts, Jan', units="Smuts's commando",
         date_start='1901-08-15', date_end='1901-09-15',
         event_type='raid', action_place='Lady Grey',
         description="Smuts crossed the Orange River near Stormberg and moved through Lady Grey and Dordrecht districts in Aug-Sep 1901, gathering Cape rebels and horses before the famous Elands River Poort ambush in Sep 1901.",
         confidence='medium', source='angloboerwar.com', note=''),
    dict(id=705, side='British', force="Molteno — Stormberg aftermath",
         commander='Gatacre, W.F.', units="3rd Division remnants; Queen's, Northumberland Fusiliers",
         date_start='1899-12-11', date_end='1900-02-01',
         event_type='retreat', action_place='Molteno',
         description="After Gatacre's disaster at Stormberg (10 Dec 1899) the battered British force fell back to Molteno railway junction; Gatacre held this position through the winter until Roberts's advance changed the strategic picture.",
         confidence='high', source='Conan Doyle ch.XII', note=''),
]

with open('data/movements.csv', 'a', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=FIELDS)
    for r in ROWS:
        w.writerow({k: str(r.get(k,'')) for k in FIELDS})

print(f"Appended {len(ROWS)} rows, IDs 693-{692+len(ROWS)}")
