"""
Final 44 gaps: remaining artillery, cavalry variants, NZ contingents.
IDs start at 649.
"""
import csv

FIELDS = ['id','side','force','commander','units','date_start','date_end',
          'event_type','from_place','to_place','action_place','description',
          'confidence','source','note']

ROWS = [
    # --- REMAINING ARTILLERY (British) ---
    ("65th Howitzer Battery Royal Field Artillery","65th Howitzer Battery RFA","British",
     "1900-02-01","Bloemfontein",
     "The 65th Howitzer Battery RFA served in Roberts's main army during the OFS advance in 1900.","medium","angloboerwar.com","north"),
    ("66th Battery Royal Field Artillery","66th Battery RFA","British",
     "1900-02-01","Pretoria",
     "The 66th Battery RFA served in the Transvaal during the advance and guerrilla phases of 1900-01.","medium","angloboerwar.com","north"),
    ("67th Battery Royal Field Artillery","67th Battery RFA","British",
     "1900-02-01","Bloemfontein",
     "The 67th Battery RFA served in Roberts's army during the OFS and Transvaal campaigns of 1900.","medium","angloboerwar.com","north"),
    ("68th Battery Royal Field Artillery","68th Battery RFA","British",
     "1900-02-01","Pretoria",
     "The 68th Battery RFA served in the Transvaal in 1900 as part of the field artillery.","medium","angloboerwar.com","north"),
    ("69th Battery Royal Field Artillery","69th Battery RFA","British",
     "1900-02-01","Pretoria",
     "The 69th Battery RFA served in the Transvaal during 1900-01.","medium","angloboerwar.com","north"),
    ("77th Battery Royal Field Artillery","77th Battery RFA","British",
     "1900-06-01","Pretoria",
     "The 77th Battery RFA served in the Transvaal during the guerrilla phase of 1900-01.","medium","angloboerwar.com","north"),
    ("78th Battery Royal Field Artillery","78th Battery RFA","British",
     "1900-06-01","Pretoria",
     "The 78th Battery RFA served in column operations in the Transvaal during 1900-01.","medium","angloboerwar.com","north"),
    ("79th Battery Royal Field Artillery","79th Battery RFA","British",
     "1900-06-01","Bloemfontein",
     "The 79th Battery RFA served in the ORC during the guerrilla phase of 1900-01.","medium","angloboerwar.com","north"),
    ("81st Battery Royal Field Artillery","81st Battery RFA","British",
     "1900-06-01","Pretoria",
     "The 81st Battery RFA served in column operations in the Transvaal during 1900-01.","medium","angloboerwar.com","north"),
    ("83rd Battery Royal Field Artillery","83rd Battery RFA","British",
     "1900-06-01","Pretoria",
     "The 83rd Battery RFA served in column operations in the Transvaal during 1900-01.","medium","angloboerwar.com","north"),
    ("85th Battery Royal Field Artillery","85th Battery RFA","British",
     "1900-06-01","Pretoria",
     "The 85th Battery RFA served in the Transvaal during 1900-01.","medium","angloboerwar.com","north"),
    ("G Battery Royal Horse Artillery","G Battery RHA","British",
     "1900-02-01","Bloemfontein",
     "G Battery RHA served with the cavalry division during Roberts's OFS advance in 1900.","high","angloboerwar.com","north"),
    ("O Battery Royal Horse Artillery","O Battery RHA","British",
     "1900-02-01","Bloemfontein",
     "O Battery RHA served with the cavalry in the OFS advance and Transvaal operations of 1900.","high","angloboerwar.com","north"),
    ("P Battery Royal Horse Artillery","P Battery RHA","British",
     "1900-02-01","Pretoria",
     "P Battery RHA served in the Transvaal during the advance and guerrilla phases.","high","angloboerwar.com","north"),
    ("R Battery Royal Horse Artillery","R Battery RHA","British",
     "1900-02-01","Pretoria",
     "R Battery RHA served in the Transvaal during 1900-01.","high","angloboerwar.com","north"),
    ("T Battery Royal Horse Artillery","T Battery RHA","British",
     "1900-01-01","Ladysmith",
     "T Battery RHA served in the Natal field artillery during the Tugela operations of 1900.","high","angloboerwar.com","north"),
    ("Royal Canadian Artillery","Royal Canadian Artillery","British",
     "1900-01-01","Pretoria",
     "The Royal Canadian Artillery battery served with Roberts's forces and in column operations in the Transvaal during 1900.","high","angloboerwar.com","north"),
    ("Royal Garrison Artillery","Royal Garrison Artillery","British",
     "1899-10-01","Cape Town",
     "Royal Garrison Artillery units manned heavy guns in the siege towns and base ports throughout the war, including at Ladysmith and Kimberley.","high","angloboerwar.com","north"),
    ("Royal Garrison Artillery (Vryheid)","Royal Garrison Artillery (Vryheid)","British",
     "1902-01-01","Vryheid",
     "A Royal Garrison Artillery detachment garrisoned the Vryheid district during the final guerrilla phase.","medium","angloboerwar.com","north"),
    ("Royal Regiment of Artillery","Royal Regiment of Artillery","British",
     "1899-10-01","Cape Town",
     "The Royal Regiment of Artillery provided field and garrison batteries across all theatres throughout the war.","high","angloboerwar.com","north"),
    # --- BOER ARTILLERY ---
    ("German Corps Artillery","German Corps Artillery","Boer",
     "1899-10-11","Pretoria",
     "The German Volunteer Corps in Transvaal service included an artillery detachment equipped with Krupp guns, serving on the eastern Transvaal front.","medium","angloboerwar.com","north"),
    ("Long Cecil (Kimberley)","Long Cecil","British",
     "1899-11-01","Kimberley",
     "Long Cecil was a 4.1-inch gun manufactured in the De Beers workshops during the Kimberley siege, designed by American engineer George Labram; it fired on Boer positions until Labram was killed by a Boer shell in February 1900.","high","Conan Doyle ch.15","north"),
    ("Transvaal Long Tom Batteries","Transvaal Long Tom","Boer",
     "1899-10-11","Pretoria",
     "The Transvaal State Artillery operated four 155mm Creusot 'Long Tom' siege guns, used against Ladysmith, Kimberley, and Mafeking; they were the most feared Boer artillery pieces of the conventional phase.","high","Conan Doyle ch.2; Handbook","north"),
    ("Transvaal State Artillery","Transvaal State Artillery","Boer",
     "1899-10-11","Pretoria",
     "The Transvaal State Artillery (ZARP Artillery) fielded Krupp field guns, Maxim pom-poms, and Creusot Long Toms on all fronts from October 1899; they were disbanded after the fall of Pretoria in June 1900.","high","Handbook; angloboerwar.com","north"),

    # --- CAVALRY VARIANTS ---
    ("10th (Prince of Wales's Own Royal) Hussars","10th Prince of Wales's Own Royal Hussars","British",
     "1899-11-01","Ladysmith",
     "The 10th Hussars served in White's Natal force and were besieged in Ladysmith from November 1899.","high","Handbook ch.V","north"),
    ("10th Prince of Wales's Own Hussars","10th Hussars","British",
     "1900-02-01","Bloemfontein",
     "The 10th Hussars (variant name) served in the OFS advance following the relief of Ladysmith.","high","angloboerwar.com","north"),
    ("12th Prince of Wales's Royal Lancers (2nd)","12th Royal Lancers (2nd deployment)","British",
     "1901-01-01","Pretoria",
     "A second deployment of the 12th Royal Lancers served in the Transvaal during the guerrilla phase of 1901-02.","medium","angloboerwar.com","north"),
    ("19th Princess of Wales's Own Hussars","19th Princess of Wales's Own Hussars","British",
     "1900-02-01","Bloemfontein",
     "The 19th Hussars served with Roberts's cavalry during the OFS and Transvaal advance in 1900.","high","angloboerwar.com","north"),
    ("2nd (Queen's Bays) Dragoon Guards","2nd Queen's Bays Dragoon Guards","British",
     "1900-01-01","Modder River",
     "The Queen's Bays (2nd Dragoon Guards) served in Methuen's cavalry and French's cavalry division during the relief of Kimberley.","high","Conan Doyle ch.14","north"),
    ("7th Princess Royal's Dragoon Guards","7th Princess Royal's Dragoon Guards","British",
     "1900-01-01","Bloemfontein",
     "The 7th Dragoon Guards (Princess Royal's) served in Roberts's cavalry during the advance through the OFS.","high","angloboerwar.com","north"),
    ("9th Queen's Royal Lancers","9th Queen's Royal Lancers","British",
     "1899-11-01","Modder River",
     "The 9th Lancers served in French's cavalry on the western front, including the famous relief-of-Kimberley dash in February 1900.","high","Conan Doyle ch.14","north"),
    ("Bengal Lancers","Bengal Lancers","British",
     "1900-02-01","Pretoria",
     "Indian Army Bengal Lancers units served in South Africa with Roberts's force during the advance and guerrilla phases.","medium","angloboerwar.com","north"),
    ("Life Guards","Life Guards","British",
     "1900-01-01","Pretoria",
     "The Life Guards (Household Cavalry) served in Roberts's army in the advance from the Modder River to Pretoria in 1900.","high","angloboerwar.com","north"),
    ("Natal Carabineers (general)","Natal Carabineers","British",
     "1899-10-01","Ladysmith",
     "The Natal Carabineers, a colonial volunteer cavalry unit, served throughout the war from the Ladysmith siege and into the Transvaal.","high","Handbook ch.V","north"),
    ("Royal Horse Guards","Royal Horse Guards","British",
     "1900-01-01","Pretoria",
     "The Royal Horse Guards (Blues) served as part of the Household Cavalry composite regiment in Roberts's advance to Pretoria in 1900.","high","angloboerwar.com","north"),

    # --- NZ CONTINGENTS 2nd-10th ---
    ("New Zealand - 2nd Contingent","New Zealand 2nd Contingent","British",
     "1900-03-01","Pretoria",
     "The New Zealand 2nd Contingent served in the Transvaal during the advance phase of 1900.","high","angloboerwar.com","north"),
    ("New Zealand - 3rd Contingent","New Zealand 3rd Contingent","British",
     "1900-07-01","Pretoria",
     "The New Zealand 3rd Contingent served in the Transvaal during the early guerrilla phase of 1900-01.","high","angloboerwar.com","north"),
    ("New Zealand - 4th Contingent","New Zealand 4th Contingent","British",
     "1900-10-01","Pretoria",
     "The New Zealand 4th Contingent served in column operations in the Transvaal during 1900-01.","high","angloboerwar.com","north"),
    ("New Zealand - 6th Contingent","New Zealand 6th Contingent","British",
     "1901-06-01","Pretoria",
     "The New Zealand 6th Contingent served in column operations in the Transvaal during 1901.","high","angloboerwar.com","north"),
    ("New Zealand - 7th Contingent","New Zealand 7th Contingent","British",
     "1901-09-01","Pretoria",
     "The New Zealand 7th Contingent served in the Transvaal during 1901-02.","high","angloboerwar.com","north"),
    ("New Zealand - 8th Contingent","New Zealand 8th Contingent","British",
     "1901-12-01","Pretoria",
     "The New Zealand 8th Contingent served in column operations in the Transvaal during 1901-02.","high","angloboerwar.com","north"),
    ("New Zealand - 9th Contingent","New Zealand 9th Contingent","British",
     "1902-01-01","Pretoria",
     "The New Zealand 9th Contingent served in the final guerrilla phase in the Transvaal during 1902.","high","angloboerwar.com","north"),
    ("New Zealand - 10th Contingent","New Zealand 10th Contingent","British",
     "1902-02-01","Pretoria",
     "The New Zealand 10th Contingent served in the Transvaal in the final months before the Peace of Vereeniging in May 1902.","high","angloboerwar.com","north"),
]

rows = []
START_ID = 649
for i, r in enumerate(ROWS):
    (force, units, side, date_start, action_place, description, confidence, source, region) = r
    rows.append({
        'id': str(START_ID + i),
        'side': side,
        'force': force,
        'commander': '',
        'units': units,
        'date_start': date_start,
        'date_end': '',
        'event_type': 'deployment',
        'from_place': '',
        'to_place': '',
        'action_place': action_place,
        'description': description,
        'confidence': confidence,
        'source': source,
        'note': '',
        '_region': region,
    })

out = 'data/_final_gaps_fragment.csv'
with open(out, 'w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=FIELDS)
    for r in rows:
        w.writerow({k: r.get(k,'') for k in FIELDS})

print(f'Written {len(rows)} rows, IDs {rows[0]["id"]}-{rows[-1]["id"]}')
print('\nA entries:')
for r in rows:
    print(f' "{r["id"]}": dict(pt="{r["action_place"]}", region="{r["_region"]}"),')
